[project]
name = "ai-engineer-bootcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "beautifulsoup4>=4.15.0",
    "catboost>=1.2.10",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.0",
    "nltk>=3.10.3",
    "numpy>=2.5.1",
    "pandas>=3.0.3",
    "psycopg2-binary>=2.9.12",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "seaborn>=0.13.2",
    "sentence-transformers>=6.0.0",
    "sqlalchemy>=2.0.51",
    "uvicorn>=0.52.1",
    "xgboost>=3.3.0",
]
