from abc import ABC, abstractmethod


class LLMClient(ABC):
    """Abstract interface for an LLM provider."""

    @abstractmethod
    def generate(self, system_prompt: str, user_prompt: str) -> str:
        """
        Generate a response from the LLM.

        Args:
            system_prompt: Instructions that define model behavior.
            user_prompt: User-specific input.

        Returns:
            The raw text response generated by the LLM.
        """
        raise NotImplementedError